{% set name = "nlptest" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nlptest-{{ version }}.tar.gz
    sha256: a5c00fdd3675e774896b048d6eecd820844811885f0c4d563489c2ec76e1944d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.12
  run:
    - python >=3.7,<3.12
    - numpy
    - pandas
    - scikit-learn
    - transformers
    - pytorch
    - sentencepiece
    - pydantic
    - nest-asyncio

about:
  home: https://github.com/JohnSnowLabs/nlptest/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/nlptest/blob/main/LICENSE
  description: John Snow Labs' NLP Test is a Python library for testing NLP models and datasets. It comes with over 50 tests covering fairness, robustness, accuracy, bias and representation for named entity recognition and text classification.
  summary: Deliver safe & effective NLP models in a few lines of code.
