{% set name = "nlptest" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nlptest-{{ version }}.tar.gz
    sha256: a5c00fdd3675e774896b048d6eecd820844811885f0c4d563489c2ec76e1944d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - numpy
    - pandas
    - scikit-learn
    - transformers
    - pytorch
    - sentencepiece
    - pydantic
    - nest-asyncio
    - wn

test:
  imports:
    - nlptest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JohnSnowLabs/nlptest/
  summary: John Snow Labs provides a library for delivering safe & effective NLP models.
  license: Apache-2.0
  license_file: LICENSE
  license_url: https://github.com/JohnSnowLabs/nlptest/blob/main/LICENSE
  description: |
      `nlptest` is an open-source Python library designed to help developers
      deliver safe and effective Natural Language Processing (NLP) models.
  
      PyPI: [https://pypi.org/project/nlptest/](https://pypi.org/project/nlptest/)
    
  dev_url: https://github.com/JohnSnowLabs/nlptest/
  doc_url: https://nlptest.org/docs/pages/docs/install

extra:
  recipe-maintainers:
    - sugatoray
    - johnsnowlab
    - luca-martial
    - ArshaanNazir
